### ISSUE TITLE
Version numbers for R packages

### ISSUE THREAD

**Issue by ghost** [ThinkR-open/prepare-for-cran#6]
This repo wrapped many pieces of useful information.  I would like to add some comments on the version numbers.  

1. The CRAN group members suggest that it is better to update the version number,  even it only addresses the issues brought up by the CRAN group member.

 2. The version number generally should have four components, major.minor.patch.dev, where dev is at least 9000.  Such as 0.1.1, 1.0.0, 0.14.5.  Please see [this page](http://r-pkgs.had.co.nz/release.html#release-version) for details.

**Comment by ColinFay** [comment]
Hi @wenlong-liu, 

Thanks for your comments. 
I've added the "bump when resubmit" rule. 

Concerning the four components of the version number, I'm not sure about that. It seems to me that the version for CRAN should only have three components, and the dev element should be drop before sending to CRAN. 

As mentioned in Hadley's book : 

> Released packages don’t have a dev component, so now you need to drop that and pick a version number based on the changes you’ve made. 

(from the chapter you linked) 

But it's good practice not to forget to drop this element, so I'll add it, thanks !

**Comment by ghost** [comment]
Hi @ColinFay 

Thanks for the reply. 

Yes, I think you are right.  I did not clearly interpret the format of version numbers.  The information in the main content regarding the version numbers is very useful and straightforward.  

I will close the issue as the comments have been addressed. 

Thanks for the efforts from you and your colleagues.
