### ISSUE TITLE
Bump your version number

### ISSUE THREAD

**Issue by hadley** [ThinkR-open/prepare-for-cran#7]
This is not correct - you should not bump version number after resubmission.

**Comment by ColinFay** [comment]
This heading is inspired by the resubmission part of the CRAN policies (https://cran.r-project.org/web/packages/policies.html#Re_002dsubmission) : 
`Updates to previously-published packages must have an increased version number unless a ‘same-version update’ is requested by the maintainers. Increasing the version number at each submission reduces confusion so is preferred even when a previous submission was not accepted.`

I guess it's not compulsory but it is preferred by the CRAN team? 

Maybe I should add that this is optional, not mandatory.

**Comment by hadley** [comment]
Oh hmmm, that was a policy change I wasn't aware of, and it's never been enforced on me 😬
